name: Darrell
favicon: null
layout_spectrum: 0.8804222613107413
typography_spectrum: 0.8793380882125348
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c1c1c1'
    - '#482076'
    - '#0f78b9'
    - '#eeb800'
  brandStrength: 0.6875
  lightness: 0.8646211414597929
  saturation: 0.08139190310612321
  rhythmicContrast: 0.48751155962236226
purpose: []
